const TEAMS_ACTION_TYPES = {
    SET_TEAMS_ARRAY: 'teams/SET_TEAMS_ARRAY',
    SET_TEAMS_CATEGORY: 'teams/SET_TEAMS_CATEGORY',
    SET_TEAMS_FILTER: 'teams/SET_TEAMS_FILTER',
    SET_TEAMS_FAVOURITE: 'teams/SET_TEAMS_FAVOURITE',
    SET_TEAMS_ARCHIVED: 'teams/SET_TEAMS_ARCHIVED',
}

export default TEAMS_ACTION_TYPES;